### PR TITLE
Port flask-babelex features to flask-babel

### PR DESCRIPTION
**Pull request by ThiefMaster**
- we switched to pytest because running the tests with unittest was a mess
- also split the tests into separate files, because that one file was already pretty huge
- added dev dependencies in a setuptools extra (like in werkzeug etc) so they can be easily installed
- added recent py3 versions in the tox envs
- domain support and caching are pretty much directly ported from flask-babelex with some changes since flask-babel got multi-directory support in the meantime
- we did NOT reformat the code, at some point adding black etc like in the pallets projects would probably be a good idea
- we did not keep support flask-babelex had for using the flask extension without having initialized it. to me that looks very much like supporting something that's not expected to work anyway..
- TODO: docs

Note: We have NOT tested it with any projects using the currently-released flask-babel version yet (so if anyone has such a project, doing so would be great). But the tests pass! ;)

- related: mrjoes/flask-babelex#20
- likely obsoletes and thus closes: #148 (even though that PR is a bit different with the new option it's adding)

@mrjoes do you want to be listed as a co-author in the commit that contains most of your babelex changes and/or somewhere in the copyright header? (if it's the latter, feel free to push a commit somewhere and we'll cherry-pick it into this PR)

### CODE REVIEW

**Comment by mrjoes** [comment]
This looks good, I will try this branch with flask-admin.

Re: credits - I'm fine either way.

**Comment by TkTech** [comment]
I hope to have time to review this on the weekend.

**Comment by ThiefMaster** [comment]
Sorry, I only noticed the second part of your comment now since there are no notifications about comments being edited. No plans to push more unless you insist on us updating the docs of course...

PS: Could you credit the flask-babelex author for originally contributing those features in whatever way you find most suitable when merging this?

**Comment by mischkadb** [comment]
Any update on this?

**Pull request merged**
