### PR TITLE
Add basic support for locales unkown by Babel

### PR DESCRIPTION
**Pull request by MarcAbonce**
Right now Flask breaks if you request content in a locale that is unknown by Babel even if the translation files actually exist.

This commit allows translations to be loaded even if the locale is unknown by Babel. Numbers and datetimes ~are returned directly~ use the default locale as a fallback.

### CODE REVIEW

**Comment by TkTech** [comment]
Sorry to be a pest, but could you add a small test? Additionally blind `excepts` are not accepted in flask-babel (and should never really be used anywhere). Catch a specific exception(s).

**Comment by a01200356** [comment]
Oh yeah, I'm really sorry about that.

I also added fallback values for numbers and datetimes in case the locale is not supported. It obviously looks horrible because there's no way of knowing the correct format for an unsupported language, but that's still better than just throwing an exception.

**Comment by a01200356** [comment]
Is there any additional issue with this PR?
I'm open to any feedback if my proposed fix is still considered unacceptable.

**Comment by TkTech** [comment]
I am okay with this as-is, I'll leave one more day for any comments otherwise this will be merged on Saturday.

**Comment by TkTech** [comment]
#557 has been merged upstream.

**Comment by MarcAbonce** [comment]
Sorry for the delay.
I just updated the Babel requirement to [version 2.6](https://github.com/python-babel/babel/releases/tag/v2.6.0) which includes [#557](https://github.com/python-babel/babel/pull/557).
That fix allows us to get a translation from a .mo file even if the locale is unknown. But if we try to create the Locale object itself, Babel will still throw an UnknownLocaleError.
Since we're using the Locale object for pretty much everything here, handling this exceptions is still needed.

**Comment by MarcAbonce** [comment]
I just updated this PR, hopefully to make it a little bit better.
Date and number formats will now fallback to the app's default locale. This way there is no need to add a separate fix for every date/number format, and the resulting format will at least look reasonable instead of just printing the "raw" number without format.
Because of that, the default locale is required to be parseable by Babel, which I think is reasonable to expect.

**Pull request closed without merging**
