### PR TITLE
Lazy-functions is only provided, when speaklater presented in system.

### PR DESCRIPTION
**Pull request by rembish**
Hi there,

I've moved `speaklater` from required packages to optional ones. So you can use flask-babel without using extra one package. Why? As a next step I want add basic debianization, 'cause I actually want install your module as a Debian package.

PS As a bonus I added `build_sphinx` and `test` to available `setup.py` options.

### CODE REVIEW

**Comment by RobertDeRose** [comment]
I wish this would have gotten merged, this is great!

**Comment by TkTech** [comment]
See #95. Speaklater is no longer required.

**Comment by RobertDeRose** [comment]
@TkTech I see that this was merged, a version bump to 0.11.0, but I don't see a tag on github for 0.11.0 and there is no pypi package for 0.11.0. I also don't see a tag for v0.10.0

Can we get tag marked with version bump changes and a matching pypi package going forward?

**Comment by TkTech** [comment]
@RobertDeRose It is already being done by bumpversion, I just neglected to push the tags. 0.11 is not on pypi yet as I intend to fix #95 which I consider a blocking release issue. `master` on github should be considered stable-but-in-progress. The version numbers are irrelevant until pushed to pypi and tagged at that point.

**Comment by RobertDeRose** [comment]
@TkTech Great! I'm glad to see speaklater integrated into Flask-Babel now. I was actaully going make a PR for this, I didn't see it. Now once 0.11.0 goes live on PyPi we can get a Debian package for Python3!!! 🎉

**Pull request closed without merging**
