### PR TITLE
Support for different text domains

### PR DESCRIPTION
**Pull request by amercader**
Both gettext and Babel make heavy use of what is called the text domain or message domain [1]. This essentially is a unique name that identifies the application, and it's also used to name the `pot`, `po` and `mo` files. The code and the documentation currently assume that the domain is always `messages`, which is fine for a standalone application. But when integrating with other applications or migrating old code bases you might need to use a different domain.

This patch adds a new optional configuration option to define the domain.

It also adds documentation for the `BABEL_TRANSLATION_DIRECTORIES` option added on 11c7b29fe.

[1]
https://www.gnu.org/software/gawk/manual/html_node/Explaining-gettext.html

### CODE REVIEW

**Comment by TkTech** [comment]
I'm trying a different take on this based on one of the earlier PRs to allow multi domains without having to create multiple Babel objects. I'd love your feedback on its usability once it's up and if it'll work for the use cases in ckan.

**Comment by sh4nks** [comment]
Any chance to get this (or something like this) merged?

**Comment by TkTech** [comment]
@amercader if you can resolve the conflicts I'm good with merging this.

**Comment by amercader** [comment]
@TkTech done!

**Comment by sh4nks** [comment]
Thank you very much adding this! Looks like I can abandon my fork.

**Pull request merged**
